[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = "1.1.6"
clap = {version="4.0.29", features=["derive"]}
enum_dispatch = "0.3.8"
nom = "7.1.3"
